-- Semantic matching v17 · run AFTER intelligence-v14.sql. Safe to re-run.
-- Adds meaning-based compatibility: "loves trekking" ≈ "into Himalayan treks".
--
-- Embeddings are generated by the `embed-profile` edge function using Supabase's
-- built-in `gte-small` model (384-dim, runs IN the edge runtime — no external API,
-- no key, ₹0 marginal cost). This migration only stores the vector and folds a
-- cosine-similarity term into match_score. Voice-first is preserved — this just
-- improves WHO we queue you with; there is still no swipe deck.

-- ═══ 1. pgvector + embedding column ═══════════════════════════════════════
create extension if not exists vector;

alter table profiles
  add column if not exists interest_embedding vector(384);

-- No ANN index needed: match_score computes a DIRECT distance between two known
-- rows (me ↔ them), not a KNN search, so a per-pair `<=>` is exact without one.

-- Convenience/debug helper: cosine similarity in [0,1] (0 when either is missing).
create or replace function interest_similarity(a uuid, b uuid) returns numeric
language sql security definer stable as $$
  select greatest(0, coalesce((
    select 1 - (pa.interest_embedding <=> pb.interest_embedding)
    from profiles pa, profiles pb
    where pa.id = a and pb.id = b
      and pa.interest_embedding is not null
      and pb.interest_embedding is not null
  ), 0))::numeric;
$$;

-- ═══ 2. match_score — same signature, + semantic term ═════════════════════
-- Identical to intelligence-v14's body, with ONE added term (up to 20 pts) for
-- embedding cosine similarity. Coalesces to 0 until both users have embeddings,
-- so behaviour is unchanged for un-embedded profiles.
create or replace function match_score(me uuid, them uuid, want text[])
returns numeric language sql security definer stable as $$
  select
    -- shared interests weighted toward tonight's picks
      24.0 * (select count(*)::numeric from unnest(
                coalesce((select interests from profiles where id = them), '{}')) i
              where i = any(want)) / greatest(array_length(want, 1), 1)
    + 12.0 * (select count(*)::numeric from unnest(
                coalesce((select interests from profiles where id = me), '{}')) i
              where i = any(coalesce((select interests from profiles where id = them), '{}')))
             / 10.0
    -- completion rate
    + 14.0 * coalesce((select avg(case when c.end_reason = 'completed' then 1.0 else 0.0 end)
                       from (select end_reason from calls
                             where (caller = them or callee = them) and state = 'ended'
                             order by created_at desc limit 20) c), 0.6)
    -- reciprocal "talk again"
    + 12.0 * coalesce((select avg(case when f.talk_again = 'yes' then 1.0
                                       when f.talk_again = 'maybe' then 0.5 else 0.0 end)
                       from call_feedback f join calls c2 on c2.id = f.call_id
                       where (c2.caller = them or c2.callee = them) and f.rater <> them), 0.5)
    -- language overlap
    + 8.0 * least(1.0, (select count(*)::numeric from unnest(
              coalesce((select languages from profiles where id = me), '{}')) l
            where l = any(coalesce((select languages from profiles where id = them), '{}'))) / 2.0)
    + (case when (select is_verified from profiles where id = them) then 5 else 0 end)
    + (case when not exists (select 1 from calls
        where ((caller = me and callee = them) or (caller = them and callee = me))
          and created_at > now() - interval '30 days') then 6 else 0 end)
    -- trait compatibility: shared strong traits (>0.5) between us
    + 6.0 * least(1.0, (
        select count(*)::numeric from
          jsonb_each_text(coalesce((select traits from conversation_traits where user_id = me), '{}')) a(k, av)
        join jsonb_each_text(coalesce((select traits from conversation_traits where user_id = them), '{}')) b(k, bv)
          on a.k = b.k
        where av::numeric > 0.5 and bv::numeric > 0.5) / 3.0)
    -- time-of-day affinity: they're usually active this hour
    + (case when exists (
        select 1 from calls
        where (caller = them or callee = them) and state = 'ended'
          and extract(hour from created_at) = extract(hour from now())) then 4 else 0 end)
    -- NEW · semantic interest similarity (embeddings). Up to 20 pts; 0 until both
    -- users are embedded, so nothing regresses for profiles without a vector yet.
    + 20.0 * interest_similarity(me, them)
$$;
